---
- hosts:  2nd-group
  connection: ssh
  gather_facts: yes

  tasks:
    - name: install package using yum
      yum: pkg={{item}} state=installed update_cache=true
      with_items: 
        - sendmail
        - wget
        - ntp
        - nfs-utils
        
