---
- hosts: 2nd-group
  connection: ssh
  gather_facts: yes

  tasks:
    - name: remove package using yum
      yum: pkg={{item}} state=absent update_cache=true
      with_items: 
        - sendmail
        - wget
        - ntp
        - nfs-utils

